# Dev environment overrides.
# Only include what's DIFFERENT from the defaults.

databases:
  billing_events:
    admin_users:
      - shawnpetersen         # individual break-glass access
    readonly_users:
      - jaren.damm            # individual read-only access
