# Generated by scaffolder — devs don't edit this file.

module "resources" {
  source = "git::https://github.com/shawnpetersen/conservice-terraform-modules.git//modules/conservice-app-resources?ref=conservice-app-resources/v1.0.0"

  app_name    = var.app_name
  env         = var.env
  region      = var.region
  config_path = path.module
  kms_key_arn = var.kms_key_arn
}
