# Generated by scaffolder — devs don't edit this file.

module "resources" {
  source = "git::https://github.com/shawnpetersen/conservice-terraform-modules.git//modules/conservice-app-resources?ref=conservice-app-resources/v1.8.0"

  app_name        = var.app_name
  env             = var.env
  region          = var.region
  config_path     = path.module
  kms_key_arn     = var.kms_key_arn
  cluster_name    = var.cluster_name
  aws_account_id  = var.aws_account_id
  tf_state_bucket = var.tf_state_bucket
}
