# Generated by scaffolder — devs don't edit this file.

variable "app_name" {
  description = "Application name"
  type        = string
}

variable "env" {
  description = "Environment: dev, stg, prod"
  type        = string
}

variable "region" {
  description = "AWS region"
  type        = string
}

variable "cluster_name" {
  description = "EKS cluster name for Pod Identity association"
  type        = string
}

variable "aws_account_id" {
  description = "AWS account ID for IAM policy ARN construction"
  type        = string
}

variable "kms_key_arn" {
  description = "KMS key ARN for encryption"
  type        = string
  default     = null
}

variable "tf_state_bucket" {
  description = "S3 bucket for Terraform state (CI role needs access)"
  type        = string
  default     = ""
}
