# Generated by scaffolder — devs don't edit this file.

variable "app_name" {
  description = "Application name"
  type        = string
}

variable "project" {
  description = "Project name for S3/Secrets naming (e.g., 'conservice')"
  type        = string
}

variable "resource_prefix" {
  description = "Short prefix for workload resource naming (e.g., 'csvc')"
  type        = string
}

variable "env" {
  description = "Environment: dev, stg, prod"
  type        = string
}

variable "region" {
  description = "AWS region"
  type        = string
}

variable "kms_key_arn" {
  description = "KMS key ARN for encryption"
  type        = string
  default     = null
}
